version: '3.7'
services:
  app:
    image: jekyll/jekyll:pages
    command: jekyll serve --livereload
    volumes:
      - .:/srv/jekyll:cached
      - /srv/jekyll/.git        # exclude
      - /srv/jekyll/_site       # exclude
    ports:
      - 4000:4000
      - 35729:35729
