version: '3.7'
services:
  app:
    image: jekyll/jekyll:pages
    command: jekyll serve --livereload
    volumes:
      - .:/srv/jekyll:cached
    tmpfs:
      - /srv/jekyll/.git
      - /srv/jekyll/_site
    ports:
      - 4000:4000
      - 35729:35729
